bind = "0.0.0.0:25565"
player-info-forwarding-mode = "modern"
ping-passthrough = "all"

[servers]
athens = "athens-mc-minecraft.minecraft.svc:25565"
thebes = "thebes-mc-minecraft.minecraft.svc:25565"
try = ["athens"]

[forced-hosts]
"athens.mc.ilysium.io" = ["athens"]
"thebes.mc.ilysium.io" = ["thebes"]

[advanced]
haproxy-protocol = true