apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity
  namespace: minecraft
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: velocity
      app.kubernetes.io/instance: velocity
  template:
    metadata:
      labels:
        app.kubernetes.io/name: velocity
        app.kubernetes.io/instance: velocity
    spec:
      serviceAccountName: velocity
      initContainers:
        - name: kubectl-install
          image: alpine/kubectl:1.36.0
          command:
            [
              "sh",
              "-c",
              "cp $(which kubectl) /tools/kubectl && chmod +x /tools/kubectl",
            ]
          volumeMounts:
            - name: tools
              mountPath: /tools
      containers:
        - name: velocity
          image: itzg/mc-proxy:2026.7.1-java25
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: TYPE
              value: "VELOCITY"
            - name: VELOCITY_VERSION
              value: 4.0.0
            - name: EULA
              value: "TRUE"
            - name: PATH
              value: "/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          ports:
            - name: minecraft
              containerPort: 25565
              protocl: TCP
          volumeMounts:
            - name: tools
              mountPath: /tools
            - name: velocity-config
              mountPath: /config/velocity.toml
              subPath: velocity.toml
            - name: forwarding-secret
              mountPath: /config/forwarding.secret
              subPath: forwarding_secret
      volumes:
        - name: tools
          emptyDir: {}
        - name: velocity-config
          configMap:
            name: velocity-runtime-config
        - name: forwarding-secret
          secret:
            secretName: velocity-forwarding-secret
