bind = "0.0.0.0:25565"
player-info-forwarding-mode = "modern"

[servers]
athens = "mc-athens.minecraft.svc:25565"
thebes = "mc-thebes.minecraft.svc:25565"
try = ["athens"]

[forced-hosts]
"athens.mc.ilysium.io" = ["athens"]
"thebes.mc.ilysium.io" = ["thebes"]

