apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-common-config
  namespace: minecraft
data:
  TYPE: "PAPER"
  EULA: "true"
  ONLINE_MODE: "false"
  LOG_LEVEL: "info"
  ENABLE_WHITELIST: "true"
  ENABLE_RCON: "true"
  RCON_PORT: 25575
  STOP_DURATION: 60