apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: server
  ports:
    - name: game
      port: 25565
    - name: rcon
      port: 25575
