apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity
spec:
  template:
    spec:
      containers:
        - name: velocity
          env:
            - name: PLUGINS_FILE
              value: "/extras/plugins.txt"
          volumeMounts:
            - name: velocity-plugins
              mountPath: /extras/plugins.txt
              subPath: plugins.txt
            - name: autostartstop-config
              mountPath: /config/plugins/autostartstop/config.yml
              subPath:
      volumes:
        - name: velocity-plugins
          configMap:
            name: velocity-plugins
        - name: autostartstop-config
          configMap:
            name: autostartstop-config
