apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velocity-forwarding-secret
  namespace: minecraft
spec:
  secretStoreRef:
    kind: SecretStore
    name: minecraft-secret-store
  refreshPolicy: Periodic
  refreshInterval: "1h0m0s"
  target:
    name: velocity-forwarding-secret
    creationPolicy: Owner
  data:
    - secretKey: forwarding_secret
      remoteRef:
        key: minecraft/velocity
        property: forwarding_secret
