apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../templates/proxy
  - externalsecrets.yml
patches:
  - path: deployment.yml
    target:
      kind: Deployment
      name: velocity
configMapGenerator:
  - name: velocity-runtime-config
    files:
      - velocity.toml=config/velocity.toml
  - name: velocity-plugins
    files:
      - plugins.txt=plugins/plugins.txt
  - name: autostartstop-config
    files:
      - config.yml=plugins/autostartstop/config.yml
generatorOptions:
  disableNameSuffixHash: true
