apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/proxy
  - externalsecrets.yml

configMapGenerator:
  - name: velocity-runtime-config
    files:
      - velocity.toml=config/velocity.toml
  - name: velocity-plugins
    files:
      - plugins.txt=plugins/plugins.txt
  - name: autostartstop-config
    files:
      - config.yml=plugins/autostartstop/config.yml

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Deployment
      name: velocity
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PLUGINS_FILE
          value: /extras/plugins.txt
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: velocity-plugins
          mountPath: /extras/plugins.txt
          subPath: plugins.txt
          readOnly: true
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: autostartstop-config
          mountPath: /config/plugins/autostartstop/config.yml
          subPath: config.yml
          readOnly: true
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: velocity-plugins
          configMap:
            name: velocity-plugins
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: autostartstop-config
          configMap:
            name: autostartstop-config
