apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-secret-store
  namespace: minecraft
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: minecraft-secret-store
  namespace: minecraft
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    vault:
      server: https://vault.ilysium.io
      path: secrets
      caProvider:
        type: ConfigMap
        name: ilysium-root-ca
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: minecraft
          serviceAccountRef:
            name: minecraft-secret-store
