apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: minecraft-route
  namespace: minecraft
spec:
  parentRefs:
    - name: perimeter-cluster-gateway
      namespace: envoy-gateway-system
      sectionName: minecraft
  rules:
    - backendRefs:
        - name: velocity
          port: 25565
