apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velocity-forwarding-secret
  namespace: minecraft
spec:
  secretStoreRef:
    kind: SecretStore
    name: minecraft-secret-store
  refreshPolicy: Periodic
  refreshInterval: "1h0m0s"
  target:
    name: velocity-forwarding-secret
    creationPolicy: Owner
  data:
    - secretKey: forwarding_secret
      remoteRef:
        key: minecraft/velocity
        property: forwarding_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paper-global-config
  namespace: minecraft
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: minecraft-secret-store
  target:
    name: paper-global-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: paper-global-tpl
            items:
              - key: paper-global.yml
  data:
    - secretKey: forwarding_secret
      remoteRef:
        key: minecraft/velocity
        property: forwarding_secret
