apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - proxy/
  - servers/athens
  - servers/thebes
configMapGenerator:
  - name: mc-common=config
    literals:
      - TYPE=PAPER
      - EULA=true
      - ONLINE_MODE=false
      - LOG_LEVEL=info
      - ENABLE_WHITELIST=true
      - ENABLE_RCON=true
      - RCON_PORT=25575
      - STOP_DURATION=60
generatorOptions:
  disableNameSuffixHash: true
