apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../templates/server
  - configmap.yml
patches:
  - path: service.yml
    target:
      kind: Service
      name: mc-server
  - path: statefulset.yml
    target:
      kind: StatefulSet
      name: mc-server
configMapGenerator:
  - name: mc-thebes-server-plugins
    files:
      - plugins.txt=plugins/plugins.txt
  - name: mc-thebes-minimotd-config
    files:
      - main.conf=plugins/minimotd/main.conf
generatorOptions:
  disableNameSuffixHash: true
