apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/server
  - externalsecrets.yml

namePrefix: thebes-

configMapGenerator:
  - name: mc-server-config
    envs:
      - server.env
  - name: mc-server-plugins
    files:
      - plugins.txt=plugins/plugins.txt

labels:
  - pairs:
      app.kubernetes.io/name: minecraft
      app.kubernetes.io/instance: thebes-mc
    includeSelectors: true

patches:
  - target:
      kind: StatefulSet
      name: mc-server
    patch: |-
      - op: replace
        path: /spec/serviceName
        value: thebes-mc

      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: thebes-mc-server-config
          - secretRef:
              name: thebes-mc-rcon-creds

      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PLUGINS_FILE
          value: /extras/plugins.txt

      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: server-plugins
          mountPath: /extras/plugins.txt
          subPath: plugins.txt
          readOnly: true

      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: paper-global
          mountPath: /config/paper-global.yml
          subPath: paper-global.yml
          readOnly: true

      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: server-plugins
            configMap:
              name: thebes-mc-server-plugins
          - name: paper-global
            secret:
              secretName: paper-global-config

generatorOptions:
  disableNameSuffixHash: true
