apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-athens-config
  namespace: minecraft
data:
  SERVER_NAME: "Athens"
  VERSION: "1.26"
  DIFFICULTY: "hard"
  MODE: "survival"
  FORCE_GAMEMODE: "survival"
  MAX_PLAYERS: 20
