apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mc-athens-rcon-creds
  namespace: minecraft
spec:
  secretStoreRef:
    kind: SecretStore
    name: minecraft-secret-store
  refreshPolicy: Periodic
  refreshInterval: "1h0m0s"
  target:
    name: mc-athens-rcon-creds
    creationPolicy: Owner
  data:
    - secretKey: RCON_PASSWORD
      remoteRef:
        key: minecraft/servers/athens/rcon
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mc-athens-paper-global
  namespace: minecraft
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: minecraft-secret-store
  target:
    name: mc-athens-paper-global
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: mc-athens-paper-global-tpl
            items:
              - key: paper-global.yml
  data:
    - secretKey: forwarding_secret
      remoteRef:
        key: minecraft/velocity
        property: forwarding_secret
