apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mc-athens-rcon-creds
  namespace: minecraft
spec:
  secretStoreRef:
    kind: SecretStore
    name: minecraft-secret-store
  refreshPolicy: Periodic
  refreshInterval: "1h0m0s"
  target:
    name: mc-athens-rcon-creds
    creationPolicy: Owner
  data:
    - secretKey: RCON_PASSWORD
      remoteRef:
        key: minecraft/servers/athens/rcon
        property: password
