apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../templates/server
  - configmap.yml
  - externalsecrets.yml
patches:
  - path: service.yml
    target:
      kind: Service
      name: mc-server
  - path: statefulset.yml
    target:
      kind: StatefulSet
      name: mc-server
configMapGenerator:
  - name: mc-athens-paper-global-tppl
    files:
      - paper-global.yml=config/paper-global.yml
  - name: mc-athens-server-plugins
    files:
      - plugins.txt=plugins/plugins.txt
  - name: mc-athens-minimotd-config
    files:
      - main.conf=plugins/minimotd/main.conf
generatorOptions:
  disableNameSuffixHash: true
