apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecrets.yml
  - helmrelease.yml

configMapGenerator:
  - name: athens-mc-plugins-config
    files:
      - minimotd-main.conf=plugins/minimotd/main.conf

generatorOptions:
  disableNameSuffixHash: true
